spring:
  config:
    activate:
      on-profile: default

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root

  mongodb:
    host: localhost
    port: 27017

  redis:
    lettuce:
      pool:
        max-active: 5 # 풀에 할당될 수 있는 커넥션 최대수 (음수=무제한)
        max-idle: 5   # 풀의 idle 커넥션 최대수(음수=무제한)
        min-idle: 2   # 풀에서 관리하는 idle 커넥션 최소 수
    host: localhost
    port: 6379
    password: 123456

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties[max.block.ms]: 1000
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest

application:
  test: kbs-def

config:
  properties:
    users:
      - name: kbs
        age: 20
      - name: ljs
        age: 15
      - name: ksy
        age: 10
    contact:
      mail: abcd@test.com
      tel: 123-4567-8910

kafka:
  topic:
    str: test.string.topic
    usr: test.user.topic


---
spring:
  config:
    activate:
      on-profile: local

application:
  test: kbs-loc

