spring:
  config:
    activate:
      on-profile: default

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root

  mongodb:
    host: localhost
    port: 27017

application:
  test: kbs-def

---
spring:
  config:
    activate:
      on-profile: local

application:
  test: kbs-loc
