spring:
  config:
    activate:
      on-profile: default

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root

  mongodb:
    host: localhost
    port: 27017

application:
  test: kbs-def

config:
  properties:
    users:
      - name: kbs
        age: 20
      - name: ljs
        age: 15
      - name: ksy
        age: 10
    contact:
      mail: abcd@test.com
      tel: 123-4567-8910


---
spring:
  config:
    activate:
      on-profile: local

application:
  test: kbs-loc

